services:
  frontend:
    build:
      context: ./sqlrunner_frontend
      dockerfile: Dockerfile
      args:
        VITE_API_URL: "http://localhost:8000"
    ports:
      - "3000:80"
    depends_on:
      - backend
    environment:
      - VITE_API_URL=http://localhost:8000
    networks:
      - sqlrunner-network

  backend:
    build:
      context: ./sqlrunner_backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    networks:
      - sqlrunner-network
networks:
  sqlrunner-network:
    driver: bridge